require:
  - rubocop-rails
  - rubocop-rspec
  - rubocop-rspec_rails

inherit_mode:
  merge:
    - Exclude

AllCops:
  NewCops: disable
  SuggestExtensions: false
  DisabledByDefault: true
  Exclude:
    - db/seeds.rb
    - db/schema.rb
    - db/migrate/*.rb
    - node_modules/**/*

Style/StringLiterals:
  Enabled: true
  EnforcedStyle: double_quotes

Style/HashSyntax:
  Enabled: true
  EnforcedShorthandSyntax: either

Lint/RequireParentheses:
  Enabled: true

Layout/TrailingWhitespace:
  Enabled: true

Layout/TrailingEmptyLines:
  Enabled: true