# fly.toml app configuration file generated for sixa on 2023-09-25T20:12:00+02:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "sixa"
primary_region = "arn"
console_command = "/rails/bin/rails console"

[build]

[[mounts]]
  source = "data"
  destination = "/data"

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = false
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]

[[statics]]
  guest_path = "/rails/public"
  url_prefix = "/"

[processes]
  # The command below is used to launch a Rails server; be sure to
  # replace with the command you're using to launch your server.
  web = "bin/rails fly:server"
  cron = "supercronic /app/crontab"

# Make sure there's only one `processes` entry under `[[services]]`
[[services]]
  processes = ["web"]
