name: main

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  main:
    name: main
    runs-on: ubuntu-latest
    steps:
    - name: executing remote ssh commands using password
      uses: appleboy/ssh-action@v1.0.3
      with:
        host: ${{ secrets.SSH_HOSTNAME }}
        username: ${{ secrets.SSH_USERNAME }}
        key: ${{ secrets.SSH_KEY }}
        port: ${{ secrets.SSH_PORT }}
        script: |
          sh /Users/henrycatalinismith/666a.se/launch-agents/pull.sh
          sh /Users/henrycatalinismith/666a.se/launch-agents/deploy.sh
